// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdijb3xEaAnbjDFTXyD6dmy0AWKqXjnFU',
    appId: '1:359738212053:web:0ab2c6e5e3341a47c4ac5c',
    messagingSenderId: '359738212053',
    projectId: 'whatsup--clone',
    authDomain: 'whatsup--clone.firebaseapp.com',
    storageBucket: 'whatsup--clone.appspot.com',
    measurementId: 'G-HBW8N0S7VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTvT7XAoeXorXkdV4cKQzZDThZ8By0UEQ',
    appId: '1:359738212053:android:5dfdaddd75177b53c4ac5c',
    messagingSenderId: '359738212053',
    projectId: 'whatsup--clone',
    storageBucket: 'whatsup--clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8VFzjno1FJWgPqPm_Sp6G-k4OcZLxts',
    appId: '1:359738212053:ios:5c9ac0f98d0796cdc4ac5c',
    messagingSenderId: '359738212053',
    projectId: 'whatsup--clone',
    storageBucket: 'whatsup--clone.appspot.com',
    iosClientId: '359738212053-g80dtsad0m8g2bqc2neo0p333fhl61r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsupClone',
  );
}
